import React from 'react'

import PropTypes from 'prop-types'

import './testimonial.css'

const Testimonial = (props) => {
  return (
    <div className={`thq-section-padding ${props.rootClassName} `}>
      <div className="testimonial-max-width thq-section-max-width">
        <div className="testimonial-container10">
          <h2 className="thq-heading-2">{props.heading1}</h2>
          <span className="testimonial-text11 thq-body-small">
            {props.content1}
          </span>
        </div>
        <div className="thq-grid-2">
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card1">
                <div className="testimonial-container12">
                  <img
                    alt={props.author1Alt}
                    src={props.author1Src}
                    className="testimonial-image1"
                  />
                  <div className="testimonial-container13">
                    <strong className="thq-body-large">
                      {props.author1Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author1Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text14 thq-body-small">
                  {props.review1}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card2">
                <div className="testimonial-container14">
                  <img
                    alt={props.author2Alt}
                    src={props.author2Src}
                    className="testimonial-image2"
                  />
                  <div className="testimonial-container15">
                    <strong className="thq-body-large">
                      {props.author2Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author2Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text17 thq-body-small">
                  {props.review2}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card3">
                <div className="testimonial-container16">
                  <img
                    alt={props.author3Alt}
                    src={props.author3Src}
                    className="testimonial-image3"
                  />
                  <div className="testimonial-container17">
                    <strong className="thq-body-large">
                      {props.author3Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author3Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text20 thq-body-small">
                  {props.review3}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div data-animated="true" className="thq-card testimonial-card4">
                <div className="testimonial-container18">
                  <img
                    alt={props.author4Alt}
                    src={props.author4Src}
                    className="testimonial-image4"
                  />
                  <div className="testimonial-container19">
                    <strong className="thq-body-large">
                      {props.author4Name}
                    </strong>
                    <span className="thq-body-small">
                      {props.author4Position}
                    </span>
                  </div>
                </div>
                <span className="testimonial-text23 thq-body-small">
                  {props.review4}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

Testimonial.defaultProps = {
  review4:
    'The comprehensive reports generated by this platform have helped us identify and address vulnerabilities effectively.',
  author3Name: 'David Johnson',
  author3Alt: 'David Johnson Image Alt Text',
  rootClassName: '',
  author1Name: 'John Doe',
  author1Position: 'Cybersecurity Analyst',
  review2:
    'The ease of use and accuracy of the scans provided by this platform have been invaluable to our team.',
  author1Src:
    'https://images.unsplash.com/photo-1523387282479-ae7166314e62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMDc4NzY2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  content1:
    'See what our users have to say about their experience with our bug-hunting platform.',
  author4Src:
    'https://images.unsplash.com/photo-1472521882609-05fb39814d60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMDc4NzY2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  author4Alt: 'Sarah Lee Image Alt Text',
  author2Position: 'IT Manager',
  review3:
    "I highly recommend this platform for anyone looking to enhance their website security measures. It's a game-changer!",
  author4Name: 'Sarah Lee',
  author4Position: 'Security Consultant',
  author1Alt: 'John Doe Image Alt Text',
  heading1: 'Testimonials',
  author3Position: 'Penetration Tester',
  author2Alt: 'Jane Smith Image Alt Text',
  review1:
    'I have been using this platform for subdomain enumeration and vulnerability scanning, and it has greatly improved our security testing process.',
  author2Src:
    'https://images.unsplash.com/photo-1519593552800-5525cdd7c6f2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMDc4NzY2Mnw&ixlib=rb-4.0.3&q=80&w=1080',
  author3Src:
    'https://images.unsplash.com/photo-1523944339743-0fe06f079939?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTczMDc4NzY2M3w&ixlib=rb-4.0.3&q=80&w=1080',
  author2Name: 'Jane Smith',
}

Testimonial.propTypes = {
  review4: PropTypes.string,
  author3Name: PropTypes.string,
  author3Alt: PropTypes.string,
  rootClassName: PropTypes.string,
  author1Name: PropTypes.string,
  author1Position: PropTypes.string,
  review2: PropTypes.string,
  author1Src: PropTypes.string,
  content1: PropTypes.string,
  author4Src: PropTypes.string,
  author4Alt: PropTypes.string,
  author2Position: PropTypes.string,
  review3: PropTypes.string,
  author4Name: PropTypes.string,
  author4Position: PropTypes.string,
  author1Alt: PropTypes.string,
  heading1: PropTypes.string,
  author3Position: PropTypes.string,
  author2Alt: PropTypes.string,
  review1: PropTypes.string,
  author2Src: PropTypes.string,
  author3Src: PropTypes.string,
  author2Name: PropTypes.string,
}

export default Testimonial
